languageCode = "en"
title = "Alexander Jophus"
theme = "hugo-coder"


[markup.highlight]
style = "github-dark"

[params]
  author = "Alexander Jophus"
  info = "Software Tinkerer"
  description = "Alexander Jophus' blog"
  keywords = "blog,developer,personal"
  avatarurl = "images/logo.jpeg"

[taxonomies]
  tag = "tags"

[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/alexanderjophus/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/AlexanderJophus/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/alexanderjosephtrelore/"
[[params.social]]
  name = "mastodon"
  icon = "fa fa-mastodon fa-2x"
  weight = 4
  url = "https://hachyderm.io/@alexanderjophus"

[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Project KIE"
  weight = 2
  url = "kie/"
  
# [deployment.targets]
# name = "personal-blog"

#   [[deployment.targets.matchers]]
#   pattern = "^.+\\.(js|css|svg|ttf)$"
#   cacheControl = "max-age=31536000, no-transform, public"
#   gzip = true

#   [[deployment.targets.matchers]]
#   pattern = "^.+\\.(png|jpg)$"
#   cacheControl = "max-age=31536000, no-transform, public"
#   gzip = false

#   [[deployment.targets.matchers]]
#   pattern = "^.+\\.(html|xml|json)$"
#   gzip = true
