languageCode = "en"
title = "Alexander Jophus"
theme = "hugo-coder"


[markup.highlight]
style = "github-dark"

[params]
author = "Alexander Jophus"
info = "Software Tinkerer"
description = "Alexander Jophus' blog"
keywords = "blog,developer,personal"
avatarurl = "images/logo.jpeg"

[taxonomies]
tag = "tags"

[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 1
url = "https://github.com/alexanderjophus/"
[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin fa-2x"
weight = 2
url = "https://www.linkedin.com/in/alexanderjosephtrelore/"
[[params.social]]
name = "mastodon"
icon = "fa fa-mastodon fa-2x"
weight = 3
url = "https://hachyderm.io/@alexanderjophus"

[[menu.main]]
name = "Blog"
weight = 1
url = "posts/"
[[menu.main]]
name = "SL"
weight = 2
url = "sl/"
[[menu.main]]
name = "Pokédex"
weight = 3
url = "https://pokedex.alexanderjophus.dev"
[[menu.main]]
name = "Game of Life"
weight = 4
url = "https://gameoflife.alexanderjophus.dev"

[services]
[services.googleAnalytics]
ID = 'G-Q0FK4PHVCM'
